# Step 1: Build the Angular app
FROM node:18 AS build

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all other project files
COPY . .

# Build the Angular app (no need for --prod)
RUN npm run build --prod

# Step 2: Serve using NGINX
FROM nginx:alpine

# Copy the build output to NGINX HTML folder
COPY --from=build /app/dist/emp-data-app /usr/share/nginx/html

# Optional: custom nginx config (if you have one)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start NGINX in the foreground
CMD ["npm","start"]

